### PR TITLE
[WIP], adding build validation

### PR DESCRIPTION
**Pull request by benjaminapetersen**
experimenting with a few ways to do this.

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
@jwforres  experimented with a few different ways to do build verification yesterday.  Running a shell script fails with this error (permissions):

```
$ ./validate.sh
/home/travis/build.sh: line 45: ./validate.sh: Permission denied
The command "./validate.sh" failed and exited with 126 during .
Your build has been stopped.
```

Any thoughts?  The beginning of the log says `This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.` but I dont think I should need sudo for this script....

**Comment by benjaminapetersen** [comment]
@jwforres Travis ping!

**Comment by jwforres** [comment]
what file permissions does the validate.sh have, I'm wondering if the "user" thats running the script doesnt have rights to execute the script

**Comment by benjaminapetersen** [comment]
Cool, will tinker with that, check if group can execute, etc.

**Comment by benjaminapetersen** [comment]
@jwforres so close, just cant get the diff script to get over end of file newline.  Isn't clear to me how this is ignored in `hack/test-assets.sh`:

``` bash
echo "Validating checked in bindata.go is up to date..."
  if ! assetdiff=$(diff -u _output/test/assets/bindata.go pkg/assets/bindata.go) ; then

    echo "$assetdiff" | head -n 10

    pushd "${OS_ROOT}/assets" > /dev/null

      if [[ "${TRAVIS-}" == "true" ]]; then
        echo ""
        echo "Bower versions..."
        bower list -o

        echo ""
        echo "NPM versions..."
        npm list
      fi

    popd > /dev/null

    exit 1
  fi
```

My version I've tried a variety of flags to tell it to ignore the newline at the end, but no luck:

``` shell
if ! assetdiff=$(diff -uB --ignore-blank-lines --ignore-space-change --strip-trailing-cr ./.tmp/build ./dist) ; then
  echo "${red}[ERROR] There is a diff that needs to be resolved (run gulp min) ${reset}"
  echo "$assetdiff"
  exit 1
else
  echo "${green}[SUCCESS] No diff ${reset}"
  exit 0
fi
```

Thoughts?

**Comment by jwforres** [comment]
doesnt look like the issue is a newline, there is an actual diff in that
content

**Comment by benjaminapetersen** [comment]
Aha! My travis n00bery solved, is now working.  Thanks!

**Pull request merged**
